# Generated by Django 2.2 on 2019-11-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='detailtext',
            new_name='maintext',
        ),
    ]
