# Generated by Django 2.2 on 2019-11-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
